FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o stresser ./Test/stresser.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/stresser .
CMD ["./stresser"]