services:
  servidor:
    build:
      context: .
      dockerfile: Server/Dockerfile
    container_name: rota-server
    ports:
      - "8080:8080/tcp"
      - "5000:5000/udp"
    networks:
      - rota-net

  sensor-01:
    build:
      context: .
      dockerfile: Sensors/Dockerfile
    container_name: sensor_01
    command: ["./sensor", "SENSOR_01"]
    networks:
      - rota-net
    depends_on:
      - servidor

  sensor-02:
    build:
      context: .
      dockerfile: Sensors/Dockerfile
    container_name: sensor_02
    command: ["./sensor", "SENSOR_02"]
    networks:
      - rota-net
    depends_on:
      - servidor

  sensor-03:
    build:
      context: .
      dockerfile: Sensors/Dockerfile
    container_name: sensor_03
    command: ["./sensor", "SENSOR_03"]
    networks:
      - rota-net
    depends_on:
      - servidor

  atuador-01:
    build:
      context: .
      dockerfile: Actuators/Dockerfile
    container_name: atuador_01
    command: ["./actuator", "atuador_01"]
    networks:
      - rota-net
    depends_on:
      - servidor

  atuador-02:
    build:
      context: .
      dockerfile: Actuators/Dockerfile
    container_name: atuador_02
    command: ["./actuator", "atuador_02"]
    networks:
      - rota-net
    depends_on:
      - servidor

  client:
    build:
      context: .
      dockerfile: User/Dockerfile
    networks:
      - rota-net
    depends_on:
      - servidor
    stdin_open: true
    tty: true
    profiles:
      - ferramentas

  test:
    build:
      context: .
      dockerfile: Test/Dockerfile
    networks:
      - rota-net
    depends_on:
      - servidor
    profiles:
      - ferramentas

networks:
  rota-net:
    driver: bridge